### ISSUE TITLE
Python bindings, segmentation fault, InverseDynamicsFormulationAccForce.data()

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/tsid#84]
Since updating to the latest version of pinocchio (branch devel, commit 2a8bd3d711e43ca449c3a75c9f3468e2b17ae4fc) I get a segmentation fault when in Python (3.5) I call the method `data()` of the class `InverseDynamicsFormulationAccForce`. I am on Ubuntu 16.04 and I am using the devel branch of TSID.

All the other methods seem to work fine, indeed I can execute the script `exercizes/ex_0_ur5_joint_space_control.py` without any problem. 

I wonder whether somebody is aware of any recent change in the Python bindings of pinocchio, especially the `Data` class, which could explain this error.

This is a minimal working example to reproduce the problem:
```
import pinocchio as se3
import tsid
import os

ERROR_MSG = 'You should set the environment variable UR5_MODEL_DIR to something like "$DEVEL_DIR/install/share"\n';
path      = os.environ.get('UR5_MODEL_DIR', ERROR_MSG)
urdf      = path + "/ur_description/urdf/ur5_robot.urdf";
srdf      = path + '/ur_description/srdf/ur5_robot.srdf'

vector = se3.StdVec_StdString()
vector.extend(item for item in path)
robot = tsid.RobotWrapper(urdf, vector, False)
formulation = tsid.InverseDynamicsFormulationAccForce("tsid", robot, False)
formulation.data()
print("Still alive")
```

**Comment by andreadelprete** [comment]
I've tried using the robotpkg version of pinocchio (2.4.3) and I still get the same problem. By debugging python3 I got the following trace:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
245	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) where
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
#1  0x00007fffe4f6394e in boost::python::converter::as_to_python_function<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, boost::python::objects::class_cref_wrapper<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, boost::python::objects::make_instance<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, boost::python::objects::value_holder<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl> > > > >::convert(void const*) () from /opt/openrobots/lib/python3.5/site-packages/pinocchio/libpinocchio_pywrap.so
#2  0x00007fffe0e69f46 in boost::python::detail::caller_arity<1u>::impl<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl> (*)(tsid::InverseDynamicsFormulationAccForce const&), boost::python::default_call_policies, boost::mpl::vector2<pinocchio::DataTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, tsid::InverseDynamicsFormulationAccForce const&> >::operator()(_object*, _object*) [clone .isra.872] [clone .constprop.1064] ()
   from /home/student/devel/install/lib/python3/dist-packages/tsid/libtsid_pywrap.so
#3  0x00007fffe39f100d in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
#4  0x00007fffe39f1208 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
#5  0x00007fffe39f9263 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
#6  0x00007fffe3e5b6d3 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<eigenpy::Exception, void (*)(eigenpy::Exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(eigenpy::Exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /opt/openrobots/lib/libeigenpy.so
#7  0x00007fffe39f901d in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
#8  0x00007fffe39ee409 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
#9  0x00000000005bfd87 in PyObject_Call ()
#10 0x00000000005409bf in PyEval_EvalFrameEx ()
#11 0x0000000000545d8b in PyEval_EvalCodeEx ()
#12 0x00000000004eca18 in ?? ()
#13 0x00000000005bfd87 in PyObject_Call ()
#14 0x00000000004fc63e in ?? ()
#15 0x00000000005bfd87 in PyObject_Call ()
#16 0x00000000005b46a9 in ?? ()
#17 0x0000000000567c9c in ?? ()
#18 0x00000000005bfd87 in PyObject_Call ()
#19 0x00000000005409bf in PyEval_EvalFrameEx ()
#20 0x0000000000544f43 in ?? ()
#21 0x0000000000545c3f in PyEval_EvalCode ()
#22 0x0000000000622642 in ?? ()
#23 0x0000000000624aea in PyRun_FileExFlags ()
#24 0x00000000006252dc in PyRun_SimpleFileExFlags ()
#25 0x000000000063e616 in Py_Main ()
#26 0x00000000004d1761 in main ()
```
I've tried to ldd the tsid and pinocchio library files and everything looks normal to me:
```
ldd /opt/openrobots/lib/python3.5/site-packages/pinocchio/libpinocchio_pywrap.so
	linux-vdso.so.1 =>  (0x00007ffe9630e000)
	libeigenpy.so => /opt/openrobots/lib/libeigenpy.so (0x00007f61940ea000)
	libboost_python-py35.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0 (0x00007f6193e9f000)
	libpinocchio.so.2.4.3 => /opt/openrobots/lib/libpinocchio.so.2.4.3 (0x00007f6193c75000)
	libboost_serialization.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.58.0 (0x00007f6193a14000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f6193810000)
	liburdfdom_world.so.0.4 => /usr/lib/x86_64-linux-gnu/liburdfdom_world.so.0.4 (0x00007f61935e5000)
	libhpp-fcl.so => /opt/openrobots/lib/libhpp-fcl.so (0x00007f6193184000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6192e02000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6192af9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f61928e3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6192519000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f61922fc000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f61920e4000)
	liburdfdom_model.so.0.4 => /usr/lib/x86_64-linux-gnu/liburdfdom_model.so.0.4 (0x00007f6191eb9000)
	libtinyxml.so.2.6.2 => /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2 (0x00007f6191ca3000)
	libconsole_bridge.so.0.2 => /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.2 (0x00007f6191a9e000)
	libassimp.so.3 => /usr/lib/x86_64-linux-gnu/libassimp.so.3 (0x00007f619120f000)
	liboctomap.so.1.9 => /opt/openrobots/lib/liboctomap.so.1.9 (0x00007f6190fa0000)
	liboctomath.so.1.9 => /opt/openrobots/lib/liboctomath.so.1.9 (0x00007f6190d99000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f61959f8000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6190b7f000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f6190974000)
student@pinocchiovbox:~/devel/src/tsid/exercizes$ ldd /home/student/devel/install/lib/python3/dist-packages/tsid/libtsid_pywrap.so
	linux-vdso.so.1 =>  (0x00007ffd85f1e000)
	libtsid.so.1.2.3-7-g8eb5 => /home/student/devel/install/lib/libtsid.so.1.2.3-7-g8eb5 (0x00007ff8b8cc2000)
	libboost_python-py35.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0 (0x00007ff8b8a77000)
	libeigenpy.so => /opt/openrobots/lib/libeigenpy.so (0x00007ff8b834c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff8b7fca000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff8b7db4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8b79ea000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007ff8b77e6000)
	libpinocchio.so.2.4.3 => /opt/openrobots/lib/libpinocchio.so.2.4.3 (0x00007ff8b75bc000)
	liburdfdom_world.so.0.4 => /usr/lib/x86_64-linux-gnu/liburdfdom_world.so.0.4 (0x00007ff8b7391000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff8b7088000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8b6e6b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff8b9390000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007ff8b6c53000)
	liburdfdom_model.so.0.4 => /usr/lib/x86_64-linux-gnu/liburdfdom_model.so.0.4 (0x00007ff8b6a28000)
	libhpp-fcl.so => /opt/openrobots/lib/libhpp-fcl.so (0x00007ff8b65c7000)
	libtinyxml.so.2.6.2 => /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2 (0x00007ff8b63b1000)
	libconsole_bridge.so.0.2 => /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.2 (0x00007ff8b61ac000)
	libassimp.so.3 => /usr/lib/x86_64-linux-gnu/libassimp.so.3 (0x00007ff8b591d000)
	liboctomap.so.1.9 => /opt/openrobots/lib/liboctomap.so.1.9 (0x00007ff8b56ae000)
	liboctomath.so.1.9 => /opt/openrobots/lib/liboctomath.so.1.9 (0x00007ff8b54a7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff8b528d000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007ff8b5082000)
```

**Comment by andreadelprete** [comment]
I've tried using the binary version of TSID (1.2.3r2) and everything works fine.

**Comment by andreadelprete** [comment]
After verifying that the binaries work fine, I have:
* uninstalled the binaries of TSID and Pinocchio
* checked out the commits of TSID and Pinocchio corresponding to the binaries, 
* compiled and installed

I still get the same segmentation fault, so it's clearly a problem with my environment. Any idea what it could be?

**Comment by andreadelprete** [comment]
Could this be due to the fact that I have two versions of Eigen?
```
student@pinocchiovbox:~/devel/src/tsid/exercizes$ dpkg -l | grep eigen
ii  libarpack2                                  3.3.0-1build2                                   amd64        Fortran77 subroutines to solve large scale eigenvalue problems
ii  libeigen3-dev                               3.3~beta1-2                                     all          lightweight C++ template library for linear algebra
ii  robotpkg-eigen-quadprog                     1.0.0r1                                         amd64        QuadProg QP solver using the Eigen3 library
ii  robotpkg-eigen3                             3.3.0                                           amd64        a C++ template library for linear algebra
ii  robotpkg-py35-eigenpy                       2.3.0                                           amd64        Eigen bindings to python
ii  ros-kinetic-eigen-conversions               1.11.9-0xenial-20181107-010715-0800             amd64        Conversion functions between: - Eigen and KDL - Eigen and geometry_msgs.
ii  ros-kinetic-tf2-eigen                       0.5.20-0xenial-20181116-181942-0800             amd64        tf2_eigen
```

**Comment by andreadelprete** [comment]
Yes, that was the problem. :)
Issue solved!
